# Generated by Django 3.1.3 on 2020-11-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('IMG', 'Image'), ('TXT', 'Text'), ('VID', 'Video'), ('AUD', 'Audio')], max_length=5)),
                ('name', models.CharField(max_length=200)),
                ('media', models.FileField(upload_to='')),
            ],
        ),
    ]
